name: bapp
services:
  bapp:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - cert
    image: bapp-web:latest
    container_name: bapp-web
    networks:
      - bapp
    restart: unless-stopped
    volumes:
      - db:/bapp/db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/bapp/"]
    entrypoint: ["/bapp/docker-entrypoint.sh"]
    command: ["/etc/bapp-server/apachectl", "start", "-DFOREGROUND"]

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: bapp-gotenberg
    networks:
      - bapp
    restart: unless-stopped
    environment:
      - CHROMIUM_IGNORE_CERTIFICATE_ERRORS=true  # required to fetch the bootstrap files
 
networks:
  bapp:

volumes:
  db:

secrets:
  cert:
    file: .secrets/ca_certificates.crt