# Generated by Django 5.2.7 on 2025-10-06 13:28

import django.db.models.deletion
import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = []

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abteilung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Abteilungsname')),
            ],
            options={
                'verbose_name': 'Abteilung',
                'verbose_name_plural': 'Abteilungen',
            },
        ),
        migrations.CreateModel(
            name='Nachweis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrieb', models.TextField(verbose_name='Betriebliche Tätigkeiten')),
                ('schule', models.TextField(verbose_name='Berufsschule')),
                ('ausbildungswoche', models.PositiveSmallIntegerField(default=web.models.ausbildungswoche_default, verbose_name='Ausbildungswoche')),
                ('jahr', models.PositiveSmallIntegerField(verbose_name='Jahr')),
                ('kalenderwoche', models.PositiveSmallIntegerField(default=web.models.kalenderwoche_default, verbose_name='Kalenderwoche')),
                ('datum_start', models.DateField(default=web.models.datum_start_default, verbose_name='Vom')),
                ('datum_end', models.DateField(default=web.models.datum_end_default, verbose_name='Bis')),
                ('fertig', models.BooleanField(default=False, verbose_name='Fertig geschrieben')),
                ('eingereicht_bei', models.CharField(max_length=100, verbose_name='Eingereicht bei')),
                ('unterschrieben', models.BooleanField(default=False, verbose_name='Unterschrieben?')),
                ('abteilung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.abteilung')),
            ],
            options={
                'verbose_name': 'Nachweis',
                'verbose_name_plural': 'Nachweise',
            },
        ),
    ]
