# Generated by Django 5.2.7 on 2025-11-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_nachweis_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachweis',
            name='ausbildungswoche',
            field=models.PositiveSmallIntegerField(verbose_name='Ausbildungswoche'),
        ),
        migrations.AlterField(
            model_name='nachweis',
            name='datum_ende',
            field=models.DateField(verbose_name='Bis'),
        ),
        migrations.AlterField(
            model_name='nachweis',
            name='datum_start',
            field=models.DateField(verbose_name='Vom'),
        ),
        migrations.AlterField(
            model_name='nachweis',
            name='jahr',
            field=models.PositiveSmallIntegerField(verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='nachweis',
            name='kalenderwoche',
            field=models.PositiveSmallIntegerField(verbose_name='Kalenderwoche'),
        ),
        migrations.AlterField(
            model_name='nachweis',
            name='nummer',
            field=models.PositiveSmallIntegerField(verbose_name='Nummer'),
        ),
    ]
