# Generated by Django 5.2.7 on 2025-11-17 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='abteilung',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
            preserve_default=False,
        ),
    ]
