# Generated by Django 5.2.7 on 2025-11-20 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_abteilung_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachweis',
            name='abteilung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.abteilung'),
        ),
    ]
