# Generated by Django 5.2.7 on 2025-12-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_abteilung_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nachweis',
            options={'ordering': ['-ausbildungswoche'], 'verbose_name': 'Nachweis', 'verbose_name_plural': 'Nachweise'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interval',
            field=models.CharField(choices=[('other', 'anderes'), ('daily', 'täglich'), ('weekly', 'wöchentlich'), ('monthly', 'monatlich')], default='other', help_text='Interval, wie häufig Nachweise erstellt werden sollten', max_length=10, verbose_name='Nachweis-Interval'),
        ),
    ]
