services:
  bapp:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/home/vscode/workspace:cached
      - venv:/home/vscode/workspace/.venv
    command: /bin/sh -c "while sleep 1000; do :; done"
    entrypoint: /home/vscode/workspace/docker-entrypoint.sh

volumes:
  venv: