services:
  bapp:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: bapp-dev
    volumes:
      - .:/home/vscode/workspace:cached
      - venv:/home/vscode/workspace/.venv
    entrypoint: []
    command: sleep infinity

volumes:
  venv: